/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ConfigGuidesRouteImport } from './routes/config-guides'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as MusicRouteImport } from './routes/music'
import { Route as NowPlayingRouteImport } from './routes/now-playing'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as AlbumsIndexRouteImport } from './routes/albums/index'
import { Route as AlbumsAlbumRouteImport } from './routes/albums/$album'
import { Route as ArtistsIndexRouteImport } from './routes/artists/index'
import { Route as ArtistsNameRouteImport } from './routes/artists/$name'
import { Route as PlaylistsIndexRouteImport } from './routes/playlists/index'
import { Route as PlaylistsNameRouteImport } from './routes/playlists/$name'
import { Route as ArtistsNameAlbumsRouteImport } from './routes/artists/$name_.albums'
import { Route as ArtistsNameAlbumsAlbumRouteImport } from './routes/artists/$name_.albums_.$album'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigGuidesRoute = ConfigGuidesRouteImport.update({
  id: '/config-guides',
  path: '/config-guides',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const NowPlayingRoute = NowPlayingRouteImport.update({
  id: '/now-playing',
  path: '/now-playing',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsIndexRoute = AlbumsIndexRouteImport.update({
  id: '/albums/',
  path: '/albums/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsAlbumRoute = AlbumsAlbumRouteImport.update({
  id: '/albums/$album',
  path: '/albums/$album',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsIndexRoute = ArtistsIndexRouteImport.update({
  id: '/artists/',
  path: '/artists/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsNameRoute = ArtistsNameRouteImport.update({
  id: '/artists/$name',
  path: '/artists/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsIndexRoute = PlaylistsIndexRouteImport.update({
  id: '/playlists/',
  path: '/playlists/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsNameRoute = PlaylistsNameRouteImport.update({
  id: '/playlists/$name',
  path: '/playlists/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsNameAlbumsRoute = ArtistsNameAlbumsRouteImport.update({
  id: '/artists/$name_/albums',
  path: '/artists/$name/albums',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsNameAlbumsAlbumRoute = ArtistsNameAlbumsAlbumRouteImport.update({
  id: '/artists/$name_/albums_/$album',
  path: '/artists/$name/albums/$album',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/config-guides': typeof ConfigGuidesRoute
  '/logs': typeof LogsRoute
  '/music': typeof MusicRoute
  '/now-playing': typeof NowPlayingRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/albums/$album': typeof AlbumsAlbumRoute
  '/artists/$name': typeof ArtistsNameRoute
  '/playlists/$name': typeof PlaylistsNameRoute
  '/albums/': typeof AlbumsIndexRoute
  '/artists/': typeof ArtistsIndexRoute
  '/playlists/': typeof PlaylistsIndexRoute
  '/artists/$name/albums': typeof ArtistsNameAlbumsRoute
  '/artists/$name/albums/$album': typeof ArtistsNameAlbumsAlbumRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/config-guides': typeof ConfigGuidesRoute
  '/logs': typeof LogsRoute
  '/music': typeof MusicRoute
  '/now-playing': typeof NowPlayingRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/albums/$album': typeof AlbumsAlbumRoute
  '/artists/$name': typeof ArtistsNameRoute
  '/playlists/$name': typeof PlaylistsNameRoute
  '/albums': typeof AlbumsIndexRoute
  '/artists': typeof ArtistsIndexRoute
  '/playlists': typeof PlaylistsIndexRoute
  '/artists/$name/albums': typeof ArtistsNameAlbumsRoute
  '/artists/$name/albums/$album': typeof ArtistsNameAlbumsAlbumRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/config-guides': typeof ConfigGuidesRoute
  '/logs': typeof LogsRoute
  '/music': typeof MusicRoute
  '/now-playing': typeof NowPlayingRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/albums/$album': typeof AlbumsAlbumRoute
  '/artists/$name': typeof ArtistsNameRoute
  '/playlists/$name': typeof PlaylistsNameRoute
  '/albums/': typeof AlbumsIndexRoute
  '/artists/': typeof ArtistsIndexRoute
  '/playlists/': typeof PlaylistsIndexRoute
  '/artists/$name_/albums': typeof ArtistsNameAlbumsRoute
  '/artists/$name_/albums_/$album': typeof ArtistsNameAlbumsAlbumRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/config-guides'
    | '/logs'
    | '/music'
    | '/now-playing'
    | '/search'
    | '/settings'
    | '/stats'
    | '/albums/$album'
    | '/artists/$name'
    | '/playlists/$name'
    | '/albums/'
    | '/artists/'
    | '/playlists/'
    | '/artists/$name/albums'
    | '/artists/$name/albums/$album'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/config-guides'
    | '/logs'
    | '/music'
    | '/now-playing'
    | '/search'
    | '/settings'
    | '/stats'
    | '/albums/$album'
    | '/artists/$name'
    | '/playlists/$name'
    | '/albums'
    | '/artists'
    | '/playlists'
    | '/artists/$name/albums'
    | '/artists/$name/albums/$album'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/config-guides'
    | '/logs'
    | '/music'
    | '/now-playing'
    | '/search'
    | '/settings'
    | '/stats'
    | '/albums/$album'
    | '/artists/$name'
    | '/playlists/$name'
    | '/albums/'
    | '/artists/'
    | '/playlists/'
    | '/artists/$name_/albums'
    | '/artists/$name_/albums_/$album'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConfigGuidesRoute: typeof ConfigGuidesRoute
  LogsRoute: typeof LogsRoute
  MusicRoute: typeof MusicRoute
  NowPlayingRoute: typeof NowPlayingRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  AlbumsAlbumRoute: typeof AlbumsAlbumRoute
  ArtistsNameRoute: typeof ArtistsNameRoute
  PlaylistsNameRoute: typeof PlaylistsNameRoute
  AlbumsIndexRoute: typeof AlbumsIndexRoute
  ArtistsIndexRoute: typeof ArtistsIndexRoute
  PlaylistsIndexRoute: typeof PlaylistsIndexRoute
  ArtistsNameAlbumsRoute: typeof ArtistsNameAlbumsRoute
  ArtistsNameAlbumsAlbumRoute: typeof ArtistsNameAlbumsAlbumRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config-guides': {
      id: '/config-guides'
      path: '/config-guides'
      fullPath: '/config-guides'
      preLoaderRoute: typeof ConfigGuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/now-playing': {
      id: '/now-playing'
      path: '/now-playing'
      fullPath: '/now-playing'
      preLoaderRoute: typeof NowPlayingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/': {
      id: '/albums/'
      path: '/albums'
      fullPath: '/albums/'
      preLoaderRoute: typeof AlbumsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/$album': {
      id: '/albums/$album'
      path: '/albums/$album'
      fullPath: '/albums/$album'
      preLoaderRoute: typeof AlbumsAlbumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/': {
      id: '/artists/'
      path: '/artists'
      fullPath: '/artists/'
      preLoaderRoute: typeof ArtistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/$name': {
      id: '/artists/$name'
      path: '/artists/$name'
      fullPath: '/artists/$name'
      preLoaderRoute: typeof ArtistsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/': {
      id: '/playlists/'
      path: '/playlists'
      fullPath: '/playlists/'
      preLoaderRoute: typeof PlaylistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/$name': {
      id: '/playlists/$name'
      path: '/playlists/$name'
      fullPath: '/playlists/$name'
      preLoaderRoute: typeof PlaylistsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/$name_/albums': {
      id: '/artists/$name_/albums'
      path: '/artists/$name/albums'
      fullPath: '/artists/$name/albums'
      preLoaderRoute: typeof ArtistsNameAlbumsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/$name_/albums_/$album': {
      id: '/artists/$name_/albums_/$album'
      path: '/artists/$name/albums/$album'
      fullPath: '/artists/$name/albums/$album'
      preLoaderRoute: typeof ArtistsNameAlbumsAlbumRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConfigGuidesRoute: ConfigGuidesRoute,
  LogsRoute: LogsRoute,
  MusicRoute: MusicRoute,
  NowPlayingRoute: NowPlayingRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  AlbumsAlbumRoute: AlbumsAlbumRoute,
  ArtistsNameRoute: ArtistsNameRoute,
  PlaylistsNameRoute: PlaylistsNameRoute,
  AlbumsIndexRoute: AlbumsIndexRoute,
  ArtistsIndexRoute: ArtistsIndexRoute,
  PlaylistsIndexRoute: PlaylistsIndexRoute,
  ArtistsNameAlbumsRoute: ArtistsNameAlbumsRoute,
  ArtistsNameAlbumsAlbumRoute: ArtistsNameAlbumsAlbumRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
